version: '3.2'
services:
  db:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - my-datavolume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password

  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - 8080:8080

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

#  auth:
#    build:
#      context: .
#      dockerfile: ./apps/auth/Dockerfile
#      target: production
#    command: npm run start:dev auth
#    env_file:
#      - ./apps/auth/.env
#    depends_on:
#      - rabbitmq
#      - db
#    volumes:
#      - .:/usr/src/app
#      - /usr/src/app/node_modules
#    ports:
#      - 3002:3002
#
#  gateway:
#    build:
#      context: .
#      dockerfile: ./apps/gateway/Dockerfile
#      target: production
#    command: npm run start:dev gateway
#    env_file:
#      - ./apps/gateway/.env
#    depends_on:
#      - db
#      - rabbitmq
#      - auth
#    volumes:
#      - .:/usr/scr/app
#      - /usr/src/app/node_modules
#    ports:
#      - 3001:3001

volumes:
  my-datavolume:
